version: '3'
services:
  aotuplan:
    image: registry.cn-shenzhen.aliyuncs.com/yangmh/autoplan:v1.0
    ports:
      - 26666:26666
    environment:
      #数据库账号
      - db_username=root
      #数据库密码
      - db_password=root
      #数据库地址
      - db_host=192.168.2.1
      #数据库名称
      - db_database=aotuplan
    restart: always

